import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import type { ZenithUserConfig } from '../config.ts';

/** Config files looked for at the root of the project, in order. */
const CONFIG_FILES = [
  'zenith.config.ts',
  'zenith.config.mts',
  'zenith.config.mjs',
  'zenith.config.js',
];

/** Everything the CLI generates lives here, and is rewritten on every run. */
export const GENERATED_DIR = '.zenith';

/** Where pages live when the config does not say otherwise. */
export const DEFAULT_DOCS_DIR = 'content';

export interface Project {
  root: string;
  configFile?: string;
  config: ZenithUserConfig;
}

/**
 * Reads `zenith.config.*`. The file is loaded by Node, so a TypeScript one may only
 * use syntax that type stripping removes, which is the case of a plain config object.
 */
export async function loadProject(root: string): Promise<Project> {
  const configFile = CONFIG_FILES.map((name) => join(root, name)).find((path) => existsSync(path));

  let config: ZenithUserConfig = { title: basename(root) };
  if (configFile) {
    const module = (await import(pathToFileURL(configFile).href)) as { default?: ZenithUserConfig };
    if (!module.default) {
      throw new Error(`${basename(configFile)} must export its ZenithDocs config as \`export default\`.`);
    }
    config = module.default;
  }

  return { root, configFile, config: { ...config, docsDir: config.docsDir ?? DEFAULT_DOCS_DIR } };
}

/**
 * Writes the generated project and returns its Astro config file, as a path relative
 * to the root: Astro joins that value onto the root, so an absolute one would double up.
 *
 * Astro loads the file with its own bundler, which is what lets it import the
 * integration from source; Node, which runs this CLI, could not.
 */
export function generateProject(project: Project): string {
  const dir = join(project.root, GENERATED_DIR);
  // An empty pages directory, because Astro warns when it cannot find one.
  mkdirSync(join(dir, 'pages'), { recursive: true });
  // The generated directory keeps itself out of version control.
  writeFileSync(join(dir, '.gitignore'), '*\n');
  writeFileSync(join(dir, 'content.config.ts'), contentConfig(project));
  writeFileSync(join(dir, 'astro.config.mjs'), astroConfig(project));
  return `${GENERATED_DIR}/astro.config.mjs`;
}

const HEADER = '// Generated by the ZenithDocs CLI, and overwritten on every run.\n';

function contentConfig({ config }: Project): string {
  return `${HEADER}import { defineCollection } from 'astro:content';
import { docsLoader, docsSchema, metaLoader, metaSchema } from 'zenith-docs/content';

const base = ${JSON.stringify(config.docsDir)};

export const collections = {
  docs: defineCollection({ loader: docsLoader({ base }), schema: docsSchema() }),
  meta: defineCollection({ loader: metaLoader({ base }), schema: metaSchema() }),
};
`;
}

function astroConfig({ config }: Project): string {
  const { site, base, ...zenith } = config;
  return `${HEADER}import { defineConfig } from 'astro/config';
import zenith from 'zenith-docs';

export default defineConfig({
  srcDir: ${JSON.stringify(GENERATED_DIR)},
  publicDir: 'public',
  outDir: 'dist',
${site ? `  site: ${JSON.stringify(site)},\n` : ''}${base ? `  base: ${JSON.stringify(base)},\n` : ''}  integrations: [zenith(${JSON.stringify(zenith, null, 2)})],
});
`;
}
